#!/bin/bash
case "$1" in
  start)
    echo "Starting WireGuard VPN..."
    sudo wg-quick up wg0
    ;;
  stop)
    echo "Stopping WireGuard VPN..."
    sudo wg-quick down wg0
    ;;
  restart)
    echo "Restarting WireGuard VPN..."
    sudo wg-quick down wg0
    sudo wg-quick up wg0
    ;;
  status)
    echo "WireGuard VPN Status:"
    sudo wg
    ;;
  *)
    echo "Usage: karyvpn {start|stop|restart|status}"
    exit 1
    ;;
esac
